# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_FreesteelPython', [dirname(__file__)])
        except ImportError:
            import _FreesteelPython
            return _FreesteelPython
        if fp is not None:
            try:
                _mod = imp.load_module('_FreesteelPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _FreesteelPython = swig_import_helper()
    del swig_import_helper
else:
    import _FreesteelPython
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _FreesteelPython.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _FreesteelPython.SwigPyIterator_value(self)
    def incr(self, n=1): return _FreesteelPython.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _FreesteelPython.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _FreesteelPython.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _FreesteelPython.SwigPyIterator_equal(self, *args)
    def copy(self): return _FreesteelPython.SwigPyIterator_copy(self)
    def next(self): return _FreesteelPython.SwigPyIterator_next(self)
    def __next__(self): return _FreesteelPython.SwigPyIterator___next__(self)
    def previous(self): return _FreesteelPython.SwigPyIterator_previous(self)
    def advance(self, *args): return _FreesteelPython.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _FreesteelPython.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _FreesteelPython.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _FreesteelPython.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _FreesteelPython.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _FreesteelPython.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _FreesteelPython.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _FreesteelPython.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class I1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, I1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, I1, name)
    __repr__ = _swig_repr
    __swig_setmethods__["lo"] = _FreesteelPython.I1_lo_set
    __swig_getmethods__["lo"] = _FreesteelPython.I1_lo_get
    if _newclass:lo = _swig_property(_FreesteelPython.I1_lo_get, _FreesteelPython.I1_lo_set)
    __swig_setmethods__["hi"] = _FreesteelPython.I1_hi_set
    __swig_getmethods__["hi"] = _FreesteelPython.I1_hi_get
    if _newclass:hi = _swig_property(_FreesteelPython.I1_hi_get, _FreesteelPython.I1_hi_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_I1(*args)
        try: self.this.append(this)
        except: self.this = this
    def SetRan(self, *args): return _FreesteelPython.I1_SetRan(self, *args)
    def SetLo(self, *args): return _FreesteelPython.I1_SetLo(self, *args)
    def SetHi(self, *args): return _FreesteelPython.I1_SetHi(self, *args)
    def Absorb(self, *args): return _FreesteelPython.I1_Absorb(self, *args)
    def Combine(self, *args): return _FreesteelPython.I1_Combine(self, *args)
    __swig_getmethods__["SCombine"] = lambda x: _FreesteelPython.I1_SCombine
    if _newclass:SCombine = staticmethod(_FreesteelPython.I1_SCombine)
    def Inflate(self, *args): return _FreesteelPython.I1_Inflate(self, *args)
    def Intersect(self, *args): return _FreesteelPython.I1_Intersect(self, *args)
    def ContainsWithin(self, *args): return _FreesteelPython.I1_ContainsWithin(self, *args)
    def Contains(self, *args): return _FreesteelPython.I1_Contains(self, *args)
    def Leng(self): return _FreesteelPython.I1_Leng(self)
    def Along(self, *args): return _FreesteelPython.I1_Along(self, *args)
    def Half(self): return _FreesteelPython.I1_Half(self)
    def InvAlong(self, *args): return _FreesteelPython.I1_InvAlong(self, *args)
    def Distance(self, *args): return _FreesteelPython.I1_Distance(self, *args)
    def PushInto(self, *args): return _FreesteelPython.I1_PushInto(self, *args)
    def PushIntoSmall(self, *args): return _FreesteelPython.I1_PushIntoSmall(self, *args)
    def __add__(self, *args): return _FreesteelPython.I1___add__(self, *args)
    def __sub__(self, *args): return _FreesteelPython.I1___sub__(self, *args)
    def __mul__(self, *args): return _FreesteelPython.I1___mul__(self, *args)
    def __div__(self, *args): return _FreesteelPython.I1___div__(self, *args)
    def __eq__(self, *args): return _FreesteelPython.I1___eq__(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_I1
    __del__ = lambda self : None;
I1_swigregister = _FreesteelPython.I1_swigregister
I1_swigregister(I1)

def I1_SCombine(*args):
  return _FreesteelPython.I1_SCombine(*args)
I1_SCombine = _FreesteelPython.I1_SCombine

MPI = _FreesteelPython.MPI
M2PI = _FreesteelPython.M2PI
class P2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, P2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, P2, name)
    __repr__ = _swig_repr
    __swig_setmethods__["u"] = _FreesteelPython.P2_u_set
    __swig_getmethods__["u"] = _FreesteelPython.P2_u_get
    if _newclass:u = _swig_property(_FreesteelPython.P2_u_get, _FreesteelPython.P2_u_set)
    __swig_setmethods__["v"] = _FreesteelPython.P2_v_set
    __swig_getmethods__["v"] = _FreesteelPython.P2_v_get
    if _newclass:v = _swig_property(_FreesteelPython.P2_v_get, _FreesteelPython.P2_v_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_P2(*args)
        try: self.this.append(this)
        except: self.this = this
    def SetVal(self, *args): return _FreesteelPython.P2_SetVal(self, *args)
    def __sub__(self, *args): return _FreesteelPython.P2___sub__(self, *args)
    def __add__(self, *args): return _FreesteelPython.P2___add__(self, *args)
    def __mul__(self, *args): return _FreesteelPython.P2___mul__(self, *args)
    def __div__(self, *args): return _FreesteelPython.P2___div__(self, *args)
    def __iadd__(self, *args): return _FreesteelPython.P2___iadd__(self, *args)
    def Lensq(self): return _FreesteelPython.P2_Lensq(self)
    def Len(self): return _FreesteelPython.P2_Len(self)
    def DArg(self): return _FreesteelPython.P2_DArg(self)
    def Arg(self): return _FreesteelPython.P2_Arg(self)
    __swig_getmethods__["InvDarg"] = lambda x: _FreesteelPython.P2_InvDarg
    if _newclass:InvDarg = staticmethod(_FreesteelPython.P2_InvDarg)
    def __eq__(self, *args): return _FreesteelPython.P2___eq__(self, *args)
    def __ne__(self, *args): return _FreesteelPython.P2___ne__(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_P2
    __del__ = lambda self : None;
P2_swigregister = _FreesteelPython.P2_swigregister
P2_swigregister(P2)

def P2_InvDarg(*args):
  return _FreesteelPython.P2_InvDarg(*args)
P2_InvDarg = _FreesteelPython.P2_InvDarg


def CPerp(*args):
  return _FreesteelPython.CPerp(*args)
CPerp = _FreesteelPython.CPerp

def APerp(*args):
  return _FreesteelPython.APerp(*args)
APerp = _FreesteelPython.APerp
class P3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, P3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, P3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _FreesteelPython.P3_x_set
    __swig_getmethods__["x"] = _FreesteelPython.P3_x_get
    if _newclass:x = _swig_property(_FreesteelPython.P3_x_get, _FreesteelPython.P3_x_set)
    __swig_setmethods__["y"] = _FreesteelPython.P3_y_set
    __swig_getmethods__["y"] = _FreesteelPython.P3_y_get
    if _newclass:y = _swig_property(_FreesteelPython.P3_y_get, _FreesteelPython.P3_y_set)
    __swig_setmethods__["z"] = _FreesteelPython.P3_z_set
    __swig_getmethods__["z"] = _FreesteelPython.P3_z_get
    if _newclass:z = _swig_property(_FreesteelPython.P3_z_get, _FreesteelPython.P3_z_set)
    def __eq__(self, *args): return _FreesteelPython.P3___eq__(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_P3(*args)
        try: self.this.append(this)
        except: self.this = this
    def __sub__(self, *args): return _FreesteelPython.P3___sub__(self, *args)
    def __add__(self, *args): return _FreesteelPython.P3___add__(self, *args)
    def __neg__(self): return _FreesteelPython.P3___neg__(self)
    def __mul__(self, *args): return _FreesteelPython.P3___mul__(self, *args)
    def __div__(self, *args): return _FreesteelPython.P3___div__(self, *args)
    def Lensq(self): return _FreesteelPython.P3_Lensq(self)
    def Len(self): return _FreesteelPython.P3_Len(self)
    __swig_getmethods__["CrossProd"] = lambda x: _FreesteelPython.P3_CrossProd
    if _newclass:CrossProd = staticmethod(_FreesteelPython.P3_CrossProd)
    __swig_destroy__ = _FreesteelPython.delete_P3
    __del__ = lambda self : None;
P3_swigregister = _FreesteelPython.P3_swigregister
P3_swigregister(P3)

def P3_CrossProd(*args):
  return _FreesteelPython.P3_CrossProd(*args)
P3_CrossProd = _FreesteelPython.P3_CrossProd


def ConvertGZ(*args):
  return _FreesteelPython.ConvertGZ(*args)
ConvertGZ = _FreesteelPython.ConvertGZ

def ConvertCZ(*args):
  return _FreesteelPython.ConvertCZ(*args)
ConvertCZ = _FreesteelPython.ConvertCZ

def ConvertLZ(*args):
  return _FreesteelPython.ConvertLZ(*args)
ConvertLZ = _FreesteelPython.ConvertLZ

def Square(*args):
  return _FreesteelPython.Square(*args)
Square = _FreesteelPython.Square

def Half(*args):
  return _FreesteelPython.Half(*args)
Half = _FreesteelPython.Half

def Along(*args):
  return _FreesteelPython.Along(*args)
Along = _FreesteelPython.Along

def InvAlong(*args):
  return _FreesteelPython.InvAlong(*args)
InvAlong = _FreesteelPython.InvAlong

def Dot(*args):
  return _FreesteelPython.Dot(*args)
Dot = _FreesteelPython.Dot

def DotLZ(*args):
  return _FreesteelPython.DotLZ(*args)
DotLZ = _FreesteelPython.DotLZ

def PosSqrt(*args):
  return _FreesteelPython.PosSqrt(*args)
PosSqrt = _FreesteelPython.PosSqrt

def Distsq(*args):
  return _FreesteelPython.Distsq(*args)
Distsq = _FreesteelPython.Distsq

def EqualP2(*args):
  return _FreesteelPython.EqualP2(*args)
EqualP2 = _FreesteelPython.EqualP2

def EqualP3(*args):
  return _FreesteelPython.EqualP3(*args)
EqualP3 = _FreesteelPython.EqualP3
class vecb1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vecb1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vecb1, name)
    __repr__ = _swig_repr
    def iterator(self): return _FreesteelPython.vecb1_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _FreesteelPython.vecb1___nonzero__(self)
    def __bool__(self): return _FreesteelPython.vecb1___bool__(self)
    def __len__(self): return _FreesteelPython.vecb1___len__(self)
    def pop(self): return _FreesteelPython.vecb1_pop(self)
    def __getslice__(self, *args): return _FreesteelPython.vecb1___getslice__(self, *args)
    def __setslice__(self, *args): return _FreesteelPython.vecb1___setslice__(self, *args)
    def __delslice__(self, *args): return _FreesteelPython.vecb1___delslice__(self, *args)
    def __delitem__(self, *args): return _FreesteelPython.vecb1___delitem__(self, *args)
    def __getitem__(self, *args): return _FreesteelPython.vecb1___getitem__(self, *args)
    def __setitem__(self, *args): return _FreesteelPython.vecb1___setitem__(self, *args)
    def append(self, *args): return _FreesteelPython.vecb1_append(self, *args)
    def empty(self): return _FreesteelPython.vecb1_empty(self)
    def size(self): return _FreesteelPython.vecb1_size(self)
    def clear(self): return _FreesteelPython.vecb1_clear(self)
    def swap(self, *args): return _FreesteelPython.vecb1_swap(self, *args)
    def get_allocator(self): return _FreesteelPython.vecb1_get_allocator(self)
    def begin(self): return _FreesteelPython.vecb1_begin(self)
    def end(self): return _FreesteelPython.vecb1_end(self)
    def rbegin(self): return _FreesteelPython.vecb1_rbegin(self)
    def rend(self): return _FreesteelPython.vecb1_rend(self)
    def pop_back(self): return _FreesteelPython.vecb1_pop_back(self)
    def erase(self, *args): return _FreesteelPython.vecb1_erase(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_vecb1(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _FreesteelPython.vecb1_push_back(self, *args)
    def front(self): return _FreesteelPython.vecb1_front(self)
    def back(self): return _FreesteelPython.vecb1_back(self)
    def assign(self, *args): return _FreesteelPython.vecb1_assign(self, *args)
    def resize(self, *args): return _FreesteelPython.vecb1_resize(self, *args)
    def insert(self, *args): return _FreesteelPython.vecb1_insert(self, *args)
    def reserve(self, *args): return _FreesteelPython.vecb1_reserve(self, *args)
    def capacity(self): return _FreesteelPython.vecb1_capacity(self)
    __swig_destroy__ = _FreesteelPython.delete_vecb1
    __del__ = lambda self : None;
vecb1_swigregister = _FreesteelPython.vecb1_swigregister
vecb1_swigregister(vecb1)

class B1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, B1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, B1, name)
    __repr__ = _swig_repr
    __swig_setmethods__["w"] = _FreesteelPython.B1_w_set
    __swig_getmethods__["w"] = _FreesteelPython.B1_w_get
    if _newclass:w = _swig_property(_FreesteelPython.B1_w_get, _FreesteelPython.B1_w_set)
    __swig_setmethods__["blower"] = _FreesteelPython.B1_blower_set
    __swig_getmethods__["blower"] = _FreesteelPython.B1_blower_get
    if _newclass:blower = _swig_property(_FreesteelPython.B1_blower_get, _FreesteelPython.B1_blower_set)
    __swig_setmethods__["binterncellbound"] = _FreesteelPython.B1_binterncellbound_set
    __swig_getmethods__["binterncellbound"] = _FreesteelPython.B1_binterncellbound_get
    if _newclass:binterncellbound = _swig_property(_FreesteelPython.B1_binterncellbound_get, _FreesteelPython.B1_binterncellbound_set)
    __swig_setmethods__["contournumber"] = _FreesteelPython.B1_contournumber_set
    __swig_getmethods__["contournumber"] = _FreesteelPython.B1_contournumber_get
    if _newclass:contournumber = _swig_property(_FreesteelPython.B1_contournumber_get, _FreesteelPython.B1_contournumber_set)
    __swig_setmethods__["cutcode"] = _FreesteelPython.B1_cutcode_set
    __swig_getmethods__["cutcode"] = _FreesteelPython.B1_cutcode_get
    if _newclass:cutcode = _swig_property(_FreesteelPython.B1_cutcode_get, _FreesteelPython.B1_cutcode_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_B1(*args)
        try: self.this.append(this)
        except: self.this = this
    def __lt__(self, *args): return _FreesteelPython.B1___lt__(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_B1
    __del__ = lambda self : None;
B1_swigregister = _FreesteelPython.B1_swigregister
B1_swigregister(B1)

class S1(vecb1):
    __swig_setmethods__ = {}
    for _s in [vecb1]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, S1, name, value)
    __swig_getmethods__ = {}
    for _s in [vecb1]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, S1, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wp"] = _FreesteelPython.S1_wp_set
    __swig_getmethods__["wp"] = _FreesteelPython.S1_wp_get
    if _newclass:wp = _swig_property(_FreesteelPython.S1_wp_get, _FreesteelPython.S1_wp_set)
    __swig_setmethods__["wrg"] = _FreesteelPython.S1_wrg_set
    __swig_getmethods__["wrg"] = _FreesteelPython.S1_wrg_get
    if _newclass:wrg = _swig_property(_FreesteelPython.S1_wrg_get, _FreesteelPython.S1_wrg_set)
    __swig_setmethods__["ftype"] = _FreesteelPython.S1_ftype_set
    __swig_getmethods__["ftype"] = _FreesteelPython.S1_ftype_get
    if _newclass:ftype = _swig_property(_FreesteelPython.S1_ftype_get, _FreesteelPython.S1_ftype_set)
    def Merge(self, *args): return _FreesteelPython.S1_Merge(self, *args)
    def Minus(self, *args): return _FreesteelPython.S1_Minus(self, *args)
    def Loclohi(self, *args): return _FreesteelPython.S1_Loclohi(self, *args)
    def Invert(self): return _FreesteelPython.S1_Invert(self)
    def Check(self): return _FreesteelPython.S1_Check(self)
    def Contains(self, *args): return _FreesteelPython.S1_Contains(self, *args)
    def ContainsRG(self, *args): return _FreesteelPython.S1_ContainsRG(self, *args)
    def SetNew(self, *args): return _FreesteelPython.S1_SetNew(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_S1(*args)
        try: self.this.append(this)
        except: self.this = this
    def SetAllCutCodes(self, *args): return _FreesteelPython.S1_SetAllCutCodes(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_S1
    __del__ = lambda self : None;
S1_swigregister = _FreesteelPython.S1_swigregister
S1_swigregister(S1)

class Partition1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Partition1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Partition1, name)
    __repr__ = _swig_repr
    def NumParts(self): return _FreesteelPython.Partition1_NumParts(self)
    def GetPart(self, *args): return _FreesteelPython.Partition1_GetPart(self, *args)
    def FindPart(self, *args): return _FreesteelPython.Partition1_FindPart(self, *args)
    def FindPartRG(self, *args): return _FreesteelPython.Partition1_FindPartRG(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_Partition1(*args)
        try: self.this.append(this)
        except: self.this = this
    def Getrg(self): return _FreesteelPython.Partition1_Getrg(self)
    __swig_destroy__ = _FreesteelPython.delete_Partition1
    __del__ = lambda self : None;
Partition1_swigregister = _FreesteelPython.Partition1_swigregister
Partition1_swigregister(Partition1)

class GSTbase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GSTbase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GSTbase, name)
    __repr__ = _swig_repr
    __swig_setmethods__["actors"] = _FreesteelPython.GSTbase_actors_set
    __swig_getmethods__["actors"] = _FreesteelPython.GSTbase_actors_get
    if _newclass:actors = _swig_property(_FreesteelPython.GSTbase_actors_get, _FreesteelPython.GSTbase_actors_set)
    __swig_setmethods__["xrg"] = _FreesteelPython.GSTbase_xrg_set
    __swig_getmethods__["xrg"] = _FreesteelPython.GSTbase_xrg_get
    if _newclass:xrg = _swig_property(_FreesteelPython.GSTbase_xrg_get, _FreesteelPython.GSTbase_xrg_set)
    __swig_setmethods__["yrg"] = _FreesteelPython.GSTbase_yrg_set
    __swig_getmethods__["yrg"] = _FreesteelPython.GSTbase_yrg_get
    if _newclass:yrg = _swig_property(_FreesteelPython.GSTbase_yrg_get, _FreesteelPython.GSTbase_yrg_set)
    __swig_setmethods__["zrg"] = _FreesteelPython.GSTbase_zrg_set
    __swig_getmethods__["zrg"] = _FreesteelPython.GSTbase_zrg_get
    if _newclass:zrg = _swig_property(_FreesteelPython.GSTbase_zrg_get, _FreesteelPython.GSTbase_zrg_set)
    def AddToRenderer(self, *args): return _FreesteelPython.GSTbase_AddToRenderer(self, *args)
    def GetVisibility(self): return _FreesteelPython.GSTbase_GetVisibility(self)
    def SetVisibility(self, *args): return _FreesteelPython.GSTbase_SetVisibility(self, *args)
    def MakeRectBoundary(self, *args): return _FreesteelPython.GSTbase_MakeRectBoundary(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_GSTbase
    __del__ = lambda self : None;
    def __init__(self): 
        this = _FreesteelPython.new_GSTbase()
        try: self.this.append(this)
        except: self.this = this
GSTbase_swigregister = _FreesteelPython.GSTbase_swigregister
GSTbase_swigregister(GSTbase)

class GSTsurface(GSTbase):
    __swig_setmethods__ = {}
    for _s in [GSTbase]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GSTsurface, name, value)
    __swig_getmethods__ = {}
    for _s in [GSTbase]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GSTsurface, name)
    __repr__ = _swig_repr
    __swig_setmethods__["stl"] = _FreesteelPython.GSTsurface_stl_set
    __swig_getmethods__["stl"] = _FreesteelPython.GSTsurface_stl_get
    if _newclass:stl = _swig_property(_FreesteelPython.GSTsurface_stl_get, _FreesteelPython.GSTsurface_stl_set)
    __swig_setmethods__["stlMap"] = _FreesteelPython.GSTsurface_stlMap_set
    __swig_getmethods__["stlMap"] = _FreesteelPython.GSTsurface_stlMap_get
    if _newclass:stlMap = _swig_property(_FreesteelPython.GSTsurface_stlMap_get, _FreesteelPython.GSTsurface_stlMap_set)
    def LoadSTL(self, *args): return _FreesteelPython.GSTsurface_LoadSTL(self, *args)
    def PushTrianglesIntoSurface(self, *args): return _FreesteelPython.GSTsurface_PushTrianglesIntoSurface(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_GSTsurface
    __del__ = lambda self : None;
    def __init__(self): 
        this = _FreesteelPython.new_GSTsurface()
        try: self.this.append(this)
        except: self.this = this
GSTsurface_swigregister = _FreesteelPython.GSTsurface_swigregister
GSTsurface_swigregister(GSTsurface)

class GSTtoolpath(GSTbase):
    __swig_setmethods__ = {}
    for _s in [GSTbase]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GSTtoolpath, name, value)
    __swig_getmethods__ = {}
    for _s in [GSTbase]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GSTtoolpath, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ftpaths"] = _FreesteelPython.GSTtoolpath_ftpaths_set
    __swig_getmethods__["ftpaths"] = _FreesteelPython.GSTtoolpath_ftpaths_get
    if _newclass:ftpaths = _swig_property(_FreesteelPython.GSTtoolpath_ftpaths_get, _FreesteelPython.GSTtoolpath_ftpaths_set)
    __swig_setmethods__["ftpolydata"] = _FreesteelPython.GSTtoolpath_ftpolydata_set
    __swig_getmethods__["ftpolydata"] = _FreesteelPython.GSTtoolpath_ftpolydata_get
    if _newclass:ftpolydata = _swig_property(_FreesteelPython.GSTtoolpath_ftpolydata_get, _FreesteelPython.GSTtoolpath_ftpolydata_set)
    __swig_setmethods__["ftpolydataMap"] = _FreesteelPython.GSTtoolpath_ftpolydataMap_set
    __swig_getmethods__["ftpolydataMap"] = _FreesteelPython.GSTtoolpath_ftpolydataMap_get
    if _newclass:ftpolydataMap = _swig_property(_FreesteelPython.GSTtoolpath_ftpolydataMap_get, _FreesteelPython.GSTtoolpath_ftpolydataMap_set)
    __swig_setmethods__["toolshape"] = _FreesteelPython.GSTtoolpath_toolshape_set
    __swig_getmethods__["toolshape"] = _FreesteelPython.GSTtoolpath_toolshape_get
    if _newclass:toolshape = _swig_property(_FreesteelPython.GSTtoolpath_toolshape_get, _FreesteelPython.GSTtoolpath_toolshape_set)
    __swig_setmethods__["bound"] = _FreesteelPython.GSTtoolpath_bound_set
    __swig_getmethods__["bound"] = _FreesteelPython.GSTtoolpath_bound_get
    if _newclass:bound = _swig_property(_FreesteelPython.GSTtoolpath_bound_get, _FreesteelPython.GSTtoolpath_bound_set)
    def UpdateFromPax(self): return _FreesteelPython.GSTtoolpath_UpdateFromPax(self)
    def SetDrawWhole(self): return _FreesteelPython.GSTtoolpath_SetDrawWhole(self)
    def addPath(self, *args): return _FreesteelPython.GSTtoolpath_addPath(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_GSTtoolpath
    __del__ = lambda self : None;
    def __init__(self): 
        this = _FreesteelPython.new_GSTtoolpath()
        try: self.this.append(this)
        except: self.this = this
GSTtoolpath_swigregister = _FreesteelPython.GSTtoolpath_swigregister
GSTtoolpath_swigregister(GSTtoolpath)

class vecPathXSeries(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vecPathXSeries, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vecPathXSeries, name)
    __repr__ = _swig_repr
    def iterator(self): return _FreesteelPython.vecPathXSeries_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _FreesteelPython.vecPathXSeries___nonzero__(self)
    def __bool__(self): return _FreesteelPython.vecPathXSeries___bool__(self)
    def __len__(self): return _FreesteelPython.vecPathXSeries___len__(self)
    def pop(self): return _FreesteelPython.vecPathXSeries_pop(self)
    def __getslice__(self, *args): return _FreesteelPython.vecPathXSeries___getslice__(self, *args)
    def __setslice__(self, *args): return _FreesteelPython.vecPathXSeries___setslice__(self, *args)
    def __delslice__(self, *args): return _FreesteelPython.vecPathXSeries___delslice__(self, *args)
    def __delitem__(self, *args): return _FreesteelPython.vecPathXSeries___delitem__(self, *args)
    def __getitem__(self, *args): return _FreesteelPython.vecPathXSeries___getitem__(self, *args)
    def __setitem__(self, *args): return _FreesteelPython.vecPathXSeries___setitem__(self, *args)
    def append(self, *args): return _FreesteelPython.vecPathXSeries_append(self, *args)
    def empty(self): return _FreesteelPython.vecPathXSeries_empty(self)
    def size(self): return _FreesteelPython.vecPathXSeries_size(self)
    def clear(self): return _FreesteelPython.vecPathXSeries_clear(self)
    def swap(self, *args): return _FreesteelPython.vecPathXSeries_swap(self, *args)
    def get_allocator(self): return _FreesteelPython.vecPathXSeries_get_allocator(self)
    def begin(self): return _FreesteelPython.vecPathXSeries_begin(self)
    def end(self): return _FreesteelPython.vecPathXSeries_end(self)
    def rbegin(self): return _FreesteelPython.vecPathXSeries_rbegin(self)
    def rend(self): return _FreesteelPython.vecPathXSeries_rend(self)
    def pop_back(self): return _FreesteelPython.vecPathXSeries_pop_back(self)
    def erase(self, *args): return _FreesteelPython.vecPathXSeries_erase(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_vecPathXSeries(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _FreesteelPython.vecPathXSeries_push_back(self, *args)
    def front(self): return _FreesteelPython.vecPathXSeries_front(self)
    def back(self): return _FreesteelPython.vecPathXSeries_back(self)
    def assign(self, *args): return _FreesteelPython.vecPathXSeries_assign(self, *args)
    def resize(self, *args): return _FreesteelPython.vecPathXSeries_resize(self, *args)
    def insert(self, *args): return _FreesteelPython.vecPathXSeries_insert(self, *args)
    def reserve(self, *args): return _FreesteelPython.vecPathXSeries_reserve(self, *args)
    def capacity(self): return _FreesteelPython.vecPathXSeries_capacity(self)
    __swig_destroy__ = _FreesteelPython.delete_vecPathXSeries
    __del__ = lambda self : None;
vecPathXSeries_swigregister = _FreesteelPython.vecPathXSeries_swigregister
vecPathXSeries_swigregister(vecPathXSeries)

class MachineParams(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MachineParams, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MachineParams, name)
    __repr__ = _swig_repr
    __swig_setmethods__["use_given_start_point"] = _FreesteelPython.MachineParams_use_given_start_point_set
    __swig_getmethods__["use_given_start_point"] = _FreesteelPython.MachineParams_use_given_start_point_get
    if _newclass:use_given_start_point = _swig_property(_FreesteelPython.MachineParams_use_given_start_point_get, _FreesteelPython.MachineParams_use_given_start_point_set)
    __swig_setmethods__["start_point"] = _FreesteelPython.MachineParams_start_point_set
    __swig_getmethods__["start_point"] = _FreesteelPython.MachineParams_start_point_get
    if _newclass:start_point = _swig_property(_FreesteelPython.MachineParams_start_point_get, _FreesteelPython.MachineParams_start_point_set)
    __swig_setmethods__["start_direction"] = _FreesteelPython.MachineParams_start_direction_set
    __swig_getmethods__["start_direction"] = _FreesteelPython.MachineParams_start_direction_get
    if _newclass:start_direction = _swig_property(_FreesteelPython.MachineParams_start_direction_get, _FreesteelPython.MachineParams_start_direction_set)
    __swig_setmethods__["minz"] = _FreesteelPython.MachineParams_minz_set
    __swig_getmethods__["minz"] = _FreesteelPython.MachineParams_minz_get
    if _newclass:minz = _swig_property(_FreesteelPython.MachineParams_minz_get, _FreesteelPython.MachineParams_minz_set)
    __swig_setmethods__["leadoffdz"] = _FreesteelPython.MachineParams_leadoffdz_set
    __swig_getmethods__["leadoffdz"] = _FreesteelPython.MachineParams_leadoffdz_get
    if _newclass:leadoffdz = _swig_property(_FreesteelPython.MachineParams_leadoffdz_get, _FreesteelPython.MachineParams_leadoffdz_set)
    __swig_setmethods__["leadofflen"] = _FreesteelPython.MachineParams_leadofflen_set
    __swig_getmethods__["leadofflen"] = _FreesteelPython.MachineParams_leadofflen_get
    if _newclass:leadofflen = _swig_property(_FreesteelPython.MachineParams_leadofflen_get, _FreesteelPython.MachineParams_leadofflen_set)
    __swig_setmethods__["leadoffrad"] = _FreesteelPython.MachineParams_leadoffrad_set
    __swig_getmethods__["leadoffrad"] = _FreesteelPython.MachineParams_leadoffrad_get
    if _newclass:leadoffrad = _swig_property(_FreesteelPython.MachineParams_leadoffrad_get, _FreesteelPython.MachineParams_leadoffrad_set)
    __swig_setmethods__["retractzheight"] = _FreesteelPython.MachineParams_retractzheight_set
    __swig_getmethods__["retractzheight"] = _FreesteelPython.MachineParams_retractzheight_get
    if _newclass:retractzheight = _swig_property(_FreesteelPython.MachineParams_retractzheight_get, _FreesteelPython.MachineParams_retractzheight_set)
    __swig_setmethods__["leadoffsamplestep"] = _FreesteelPython.MachineParams_leadoffsamplestep_set
    __swig_getmethods__["leadoffsamplestep"] = _FreesteelPython.MachineParams_leadoffsamplestep_get
    if _newclass:leadoffsamplestep = _swig_property(_FreesteelPython.MachineParams_leadoffsamplestep_get, _FreesteelPython.MachineParams_leadoffsamplestep_set)
    __swig_setmethods__["toolcornerrad"] = _FreesteelPython.MachineParams_toolcornerrad_set
    __swig_getmethods__["toolcornerrad"] = _FreesteelPython.MachineParams_toolcornerrad_get
    if _newclass:toolcornerrad = _swig_property(_FreesteelPython.MachineParams_toolcornerrad_get, _FreesteelPython.MachineParams_toolcornerrad_set)
    __swig_setmethods__["toolflatrad"] = _FreesteelPython.MachineParams_toolflatrad_set
    __swig_getmethods__["toolflatrad"] = _FreesteelPython.MachineParams_toolflatrad_get
    if _newclass:toolflatrad = _swig_property(_FreesteelPython.MachineParams_toolflatrad_get, _FreesteelPython.MachineParams_toolflatrad_set)
    __swig_setmethods__["samplestep"] = _FreesteelPython.MachineParams_samplestep_set
    __swig_getmethods__["samplestep"] = _FreesteelPython.MachineParams_samplestep_get
    if _newclass:samplestep = _swig_property(_FreesteelPython.MachineParams_samplestep_get, _FreesteelPython.MachineParams_samplestep_set)
    __swig_setmethods__["stepdown"] = _FreesteelPython.MachineParams_stepdown_set
    __swig_getmethods__["stepdown"] = _FreesteelPython.MachineParams_stepdown_get
    if _newclass:stepdown = _swig_property(_FreesteelPython.MachineParams_stepdown_get, _FreesteelPython.MachineParams_stepdown_set)
    __swig_setmethods__["clearcuspheight"] = _FreesteelPython.MachineParams_clearcuspheight_set
    __swig_getmethods__["clearcuspheight"] = _FreesteelPython.MachineParams_clearcuspheight_get
    if _newclass:clearcuspheight = _swig_property(_FreesteelPython.MachineParams_clearcuspheight_get, _FreesteelPython.MachineParams_clearcuspheight_set)
    __swig_setmethods__["triangleweaveres"] = _FreesteelPython.MachineParams_triangleweaveres_set
    __swig_getmethods__["triangleweaveres"] = _FreesteelPython.MachineParams_triangleweaveres_get
    if _newclass:triangleweaveres = _swig_property(_FreesteelPython.MachineParams_triangleweaveres_get, _FreesteelPython.MachineParams_triangleweaveres_set)
    __swig_setmethods__["flatradweaveres"] = _FreesteelPython.MachineParams_flatradweaveres_set
    __swig_getmethods__["flatradweaveres"] = _FreesteelPython.MachineParams_flatradweaveres_get
    if _newclass:flatradweaveres = _swig_property(_FreesteelPython.MachineParams_flatradweaveres_get, _FreesteelPython.MachineParams_flatradweaveres_set)
    __swig_setmethods__["dchangright"] = _FreesteelPython.MachineParams_dchangright_set
    __swig_getmethods__["dchangright"] = _FreesteelPython.MachineParams_dchangright_get
    if _newclass:dchangright = _swig_property(_FreesteelPython.MachineParams_dchangright_get, _FreesteelPython.MachineParams_dchangright_set)
    __swig_setmethods__["dchangrightoncontour"] = _FreesteelPython.MachineParams_dchangrightoncontour_set
    __swig_getmethods__["dchangrightoncontour"] = _FreesteelPython.MachineParams_dchangrightoncontour_get
    if _newclass:dchangrightoncontour = _swig_property(_FreesteelPython.MachineParams_dchangrightoncontour_get, _FreesteelPython.MachineParams_dchangrightoncontour_set)
    __swig_setmethods__["dchangleft"] = _FreesteelPython.MachineParams_dchangleft_set
    __swig_getmethods__["dchangleft"] = _FreesteelPython.MachineParams_dchangleft_get
    if _newclass:dchangleft = _swig_property(_FreesteelPython.MachineParams_dchangleft_get, _FreesteelPython.MachineParams_dchangleft_set)
    __swig_setmethods__["dchangefreespace"] = _FreesteelPython.MachineParams_dchangefreespace_set
    __swig_getmethods__["dchangefreespace"] = _FreesteelPython.MachineParams_dchangefreespace_get
    if _newclass:dchangefreespace = _swig_property(_FreesteelPython.MachineParams_dchangefreespace_get, _FreesteelPython.MachineParams_dchangefreespace_set)
    __swig_setmethods__["sidecutdisplch"] = _FreesteelPython.MachineParams_sidecutdisplch_set
    __swig_getmethods__["sidecutdisplch"] = _FreesteelPython.MachineParams_sidecutdisplch_get
    if _newclass:sidecutdisplch = _swig_property(_FreesteelPython.MachineParams_sidecutdisplch_get, _FreesteelPython.MachineParams_sidecutdisplch_set)
    __swig_setmethods__["fcut"] = _FreesteelPython.MachineParams_fcut_set
    __swig_getmethods__["fcut"] = _FreesteelPython.MachineParams_fcut_get
    if _newclass:fcut = _swig_property(_FreesteelPython.MachineParams_fcut_get, _FreesteelPython.MachineParams_fcut_set)
    __swig_setmethods__["fretract"] = _FreesteelPython.MachineParams_fretract_set
    __swig_getmethods__["fretract"] = _FreesteelPython.MachineParams_fretract_get
    if _newclass:fretract = _swig_property(_FreesteelPython.MachineParams_fretract_get, _FreesteelPython.MachineParams_fretract_set)
    __swig_setmethods__["thintol"] = _FreesteelPython.MachineParams_thintol_set
    __swig_getmethods__["thintol"] = _FreesteelPython.MachineParams_thintol_get
    if _newclass:thintol = _swig_property(_FreesteelPython.MachineParams_thintol_get, _FreesteelPython.MachineParams_thintol_set)
    def __init__(self): 
        this = _FreesteelPython.new_MachineParams()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_MachineParams
    __del__ = lambda self : None;
MachineParams_swigregister = _FreesteelPython.MachineParams_swigregister
MachineParams_swigregister(MachineParams)

class CoreRoughGeneration(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CoreRoughGeneration, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CoreRoughGeneration, name)
    __repr__ = _swig_repr
    __swig_setmethods__["machxrg"] = _FreesteelPython.CoreRoughGeneration_machxrg_set
    __swig_getmethods__["machxrg"] = _FreesteelPython.CoreRoughGeneration_machxrg_get
    if _newclass:machxrg = _swig_property(_FreesteelPython.CoreRoughGeneration_machxrg_get, _FreesteelPython.CoreRoughGeneration_machxrg_set)
    __swig_setmethods__["machyrg"] = _FreesteelPython.CoreRoughGeneration_machyrg_set
    __swig_getmethods__["machyrg"] = _FreesteelPython.CoreRoughGeneration_machyrg_get
    if _newclass:machyrg = _swig_property(_FreesteelPython.CoreRoughGeneration_machyrg_get, _FreesteelPython.CoreRoughGeneration_machyrg_set)
    __swig_setmethods__["tsbound"] = _FreesteelPython.CoreRoughGeneration_tsbound_set
    __swig_getmethods__["tsbound"] = _FreesteelPython.CoreRoughGeneration_tsbound_get
    if _newclass:tsbound = _swig_property(_FreesteelPython.CoreRoughGeneration_tsbound_get, _FreesteelPython.CoreRoughGeneration_tsbound_set)
    __swig_setmethods__["pa2gg"] = _FreesteelPython.CoreRoughGeneration_pa2gg_set
    __swig_getmethods__["pa2gg"] = _FreesteelPython.CoreRoughGeneration_pa2gg_get
    if _newclass:pa2gg = _swig_property(_FreesteelPython.CoreRoughGeneration_pa2gg_get, _FreesteelPython.CoreRoughGeneration_pa2gg_set)
    __swig_setmethods__["wc"] = _FreesteelPython.CoreRoughGeneration_wc_set
    __swig_getmethods__["wc"] = _FreesteelPython.CoreRoughGeneration_wc_get
    if _newclass:wc = _swig_property(_FreesteelPython.CoreRoughGeneration_wc_get, _FreesteelPython.CoreRoughGeneration_wc_set)
    __swig_setmethods__["trad"] = _FreesteelPython.CoreRoughGeneration_trad_set
    __swig_getmethods__["trad"] = _FreesteelPython.CoreRoughGeneration_trad_get
    if _newclass:trad = _swig_property(_FreesteelPython.CoreRoughGeneration_trad_get, _FreesteelPython.CoreRoughGeneration_trad_set)
    __swig_setmethods__["countfreespacesteps"] = _FreesteelPython.CoreRoughGeneration_countfreespacesteps_set
    __swig_getmethods__["countfreespacesteps"] = _FreesteelPython.CoreRoughGeneration_countfreespacesteps_get
    if _newclass:countfreespacesteps = _swig_property(_FreesteelPython.CoreRoughGeneration_countfreespacesteps_get, _FreesteelPython.CoreRoughGeneration_countfreespacesteps_set)
    __swig_setmethods__["pathxb"] = _FreesteelPython.CoreRoughGeneration_pathxb_set
    __swig_getmethods__["pathxb"] = _FreesteelPython.CoreRoughGeneration_pathxb_get
    if _newclass:pathxb = _swig_property(_FreesteelPython.CoreRoughGeneration_pathxb_get, _FreesteelPython.CoreRoughGeneration_pathxb_set)
    __swig_setmethods__["bcellixs"] = _FreesteelPython.CoreRoughGeneration_bcellixs_set
    __swig_getmethods__["bcellixs"] = _FreesteelPython.CoreRoughGeneration_bcellixs_get
    if _newclass:bcellixs = _swig_property(_FreesteelPython.CoreRoughGeneration_bcellixs_get, _FreesteelPython.CoreRoughGeneration_bcellixs_set)
    __swig_setmethods__["bPrevPointDoubleRange"] = _FreesteelPython.CoreRoughGeneration_bPrevPointDoubleRange_set
    __swig_getmethods__["bPrevPointDoubleRange"] = _FreesteelPython.CoreRoughGeneration_bPrevPointDoubleRange_get
    if _newclass:bPrevPointDoubleRange = _swig_property(_FreesteelPython.CoreRoughGeneration_bPrevPointDoubleRange_get, _FreesteelPython.CoreRoughGeneration_bPrevPointDoubleRange_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_CoreRoughGeneration(*args)
        try: self.this.append(this)
        except: self.this = this
    def FindGoStart(self, *args): return _FreesteelPython.CoreRoughGeneration_FindGoStart(self, *args)
    def RestartAtBCI(self, *args): return _FreesteelPython.CoreRoughGeneration_RestartAtBCI(self, *args)
    def ChangeBearing(self, *args): return _FreesteelPython.CoreRoughGeneration_ChangeBearing(self, *args)
    def AddPoint(self, *args): return _FreesteelPython.CoreRoughGeneration_AddPoint(self, *args)
    def GrabberAlg(self, *args): return _FreesteelPython.CoreRoughGeneration_GrabberAlg(self, *args)
    def TrackLink(self, *args): return _FreesteelPython.CoreRoughGeneration_TrackLink(self, *args)
    def setWeave(self, *args): return _FreesteelPython.CoreRoughGeneration_setWeave(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_CoreRoughGeneration
    __del__ = lambda self : None;
CoreRoughGeneration_swigregister = _FreesteelPython.CoreRoughGeneration_swigregister
CoreRoughGeneration_swigregister(CoreRoughGeneration)


def MakeCorerough(*args):
  return _FreesteelPython.MakeCorerough(*args)
MakeCorerough = _FreesteelPython.MakeCorerough
class vecP2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vecP2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vecP2, name)
    __repr__ = _swig_repr
    def iterator(self): return _FreesteelPython.vecP2_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _FreesteelPython.vecP2___nonzero__(self)
    def __bool__(self): return _FreesteelPython.vecP2___bool__(self)
    def __len__(self): return _FreesteelPython.vecP2___len__(self)
    def pop(self): return _FreesteelPython.vecP2_pop(self)
    def __getslice__(self, *args): return _FreesteelPython.vecP2___getslice__(self, *args)
    def __setslice__(self, *args): return _FreesteelPython.vecP2___setslice__(self, *args)
    def __delslice__(self, *args): return _FreesteelPython.vecP2___delslice__(self, *args)
    def __delitem__(self, *args): return _FreesteelPython.vecP2___delitem__(self, *args)
    def __getitem__(self, *args): return _FreesteelPython.vecP2___getitem__(self, *args)
    def __setitem__(self, *args): return _FreesteelPython.vecP2___setitem__(self, *args)
    def append(self, *args): return _FreesteelPython.vecP2_append(self, *args)
    def empty(self): return _FreesteelPython.vecP2_empty(self)
    def size(self): return _FreesteelPython.vecP2_size(self)
    def clear(self): return _FreesteelPython.vecP2_clear(self)
    def swap(self, *args): return _FreesteelPython.vecP2_swap(self, *args)
    def get_allocator(self): return _FreesteelPython.vecP2_get_allocator(self)
    def begin(self): return _FreesteelPython.vecP2_begin(self)
    def end(self): return _FreesteelPython.vecP2_end(self)
    def rbegin(self): return _FreesteelPython.vecP2_rbegin(self)
    def rend(self): return _FreesteelPython.vecP2_rend(self)
    def pop_back(self): return _FreesteelPython.vecP2_pop_back(self)
    def erase(self, *args): return _FreesteelPython.vecP2_erase(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_vecP2(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _FreesteelPython.vecP2_push_back(self, *args)
    def front(self): return _FreesteelPython.vecP2_front(self)
    def back(self): return _FreesteelPython.vecP2_back(self)
    def assign(self, *args): return _FreesteelPython.vecP2_assign(self, *args)
    def resize(self, *args): return _FreesteelPython.vecP2_resize(self, *args)
    def insert(self, *args): return _FreesteelPython.vecP2_insert(self, *args)
    def reserve(self, *args): return _FreesteelPython.vecP2_reserve(self, *args)
    def capacity(self): return _FreesteelPython.vecP2_capacity(self)
    __swig_destroy__ = _FreesteelPython.delete_vecP2
    __del__ = lambda self : None;
vecP2_swigregister = _FreesteelPython.vecP2_swigregister
vecP2_swigregister(vecP2)

class vecint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vecint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vecint, name)
    __repr__ = _swig_repr
    def iterator(self): return _FreesteelPython.vecint_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _FreesteelPython.vecint___nonzero__(self)
    def __bool__(self): return _FreesteelPython.vecint___bool__(self)
    def __len__(self): return _FreesteelPython.vecint___len__(self)
    def pop(self): return _FreesteelPython.vecint_pop(self)
    def __getslice__(self, *args): return _FreesteelPython.vecint___getslice__(self, *args)
    def __setslice__(self, *args): return _FreesteelPython.vecint___setslice__(self, *args)
    def __delslice__(self, *args): return _FreesteelPython.vecint___delslice__(self, *args)
    def __delitem__(self, *args): return _FreesteelPython.vecint___delitem__(self, *args)
    def __getitem__(self, *args): return _FreesteelPython.vecint___getitem__(self, *args)
    def __setitem__(self, *args): return _FreesteelPython.vecint___setitem__(self, *args)
    def append(self, *args): return _FreesteelPython.vecint_append(self, *args)
    def empty(self): return _FreesteelPython.vecint_empty(self)
    def size(self): return _FreesteelPython.vecint_size(self)
    def clear(self): return _FreesteelPython.vecint_clear(self)
    def swap(self, *args): return _FreesteelPython.vecint_swap(self, *args)
    def get_allocator(self): return _FreesteelPython.vecint_get_allocator(self)
    def begin(self): return _FreesteelPython.vecint_begin(self)
    def end(self): return _FreesteelPython.vecint_end(self)
    def rbegin(self): return _FreesteelPython.vecint_rbegin(self)
    def rend(self): return _FreesteelPython.vecint_rend(self)
    def pop_back(self): return _FreesteelPython.vecint_pop_back(self)
    def erase(self, *args): return _FreesteelPython.vecint_erase(self, *args)
    def __init__(self, *args): 
        this = _FreesteelPython.new_vecint(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _FreesteelPython.vecint_push_back(self, *args)
    def front(self): return _FreesteelPython.vecint_front(self)
    def back(self): return _FreesteelPython.vecint_back(self)
    def assign(self, *args): return _FreesteelPython.vecint_assign(self, *args)
    def resize(self, *args): return _FreesteelPython.vecint_resize(self, *args)
    def insert(self, *args): return _FreesteelPython.vecint_insert(self, *args)
    def reserve(self, *args): return _FreesteelPython.vecint_reserve(self, *args)
    def capacity(self): return _FreesteelPython.vecint_capacity(self)
    __swig_destroy__ = _FreesteelPython.delete_vecint
    __del__ = lambda self : None;
vecint_swigregister = _FreesteelPython.vecint_swigregister
vecint_swigregister(vecint)

class PathXSeries(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PathXSeries, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PathXSeries, name)
    __repr__ = _swig_repr
    __swig_setmethods__["z"] = _FreesteelPython.PathXSeries_z_set
    __swig_getmethods__["z"] = _FreesteelPython.PathXSeries_z_get
    if _newclass:z = _swig_property(_FreesteelPython.PathXSeries_z_get, _FreesteelPython.PathXSeries_z_set)
    __swig_setmethods__["pths"] = _FreesteelPython.PathXSeries_pths_set
    __swig_getmethods__["pths"] = _FreesteelPython.PathXSeries_pths_get
    if _newclass:pths = _swig_property(_FreesteelPython.PathXSeries_pths_get, _FreesteelPython.PathXSeries_pths_set)
    __swig_setmethods__["brks"] = _FreesteelPython.PathXSeries_brks_set
    __swig_getmethods__["brks"] = _FreesteelPython.PathXSeries_brks_get
    if _newclass:brks = _swig_property(_FreesteelPython.PathXSeries_brks_get, _FreesteelPython.PathXSeries_brks_set)
    __swig_setmethods__["linkpths"] = _FreesteelPython.PathXSeries_linkpths_set
    __swig_getmethods__["linkpths"] = _FreesteelPython.PathXSeries_linkpths_get
    if _newclass:linkpths = _swig_property(_FreesteelPython.PathXSeries_linkpths_get, _FreesteelPython.PathXSeries_linkpths_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_PathXSeries(*args)
        try: self.this.append(this)
        except: self.this = this
    def Add(self, *args): return _FreesteelPython.PathXSeries_Add(self, *args)
    def Append(self, *args): return _FreesteelPython.PathXSeries_Append(self, *args)
    def Break(self): return _FreesteelPython.PathXSeries_Break(self)
    def Pop_back(self): return _FreesteelPython.PathXSeries_Pop_back(self)
    def GetNbrks(self): return _FreesteelPython.PathXSeries_GetNbrks(self)
    def GetBrkIndex(self, *args): return _FreesteelPython.PathXSeries_GetBrkIndex(self, *args)
    def GetNlnks(self, *args): return _FreesteelPython.PathXSeries_GetNlnks(self, *args)
    def GetLinkX(self, *args): return _FreesteelPython.PathXSeries_GetLinkX(self, *args)
    def GetLinkY(self, *args): return _FreesteelPython.PathXSeries_GetLinkY(self, *args)
    def GetLinkZ(self, *args): return _FreesteelPython.PathXSeries_GetLinkZ(self, *args)
    def GetNpts(self): return _FreesteelPython.PathXSeries_GetNpts(self)
    def GetX(self, *args): return _FreesteelPython.PathXSeries_GetX(self, *args)
    def GetY(self, *args): return _FreesteelPython.PathXSeries_GetY(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_PathXSeries
    __del__ = lambda self : None;
PathXSeries_swigregister = _FreesteelPython.PathXSeries_swigregister
PathXSeries_swigregister(PathXSeries)

class ckpline(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ckpline, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ckpline, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iseg"] = _FreesteelPython.ckpline_iseg_set
    __swig_getmethods__["iseg"] = _FreesteelPython.ckpline_iseg_get
    if _newclass:iseg = _swig_property(_FreesteelPython.ckpline_iseg_get, _FreesteelPython.ckpline_iseg_set)
    __swig_setmethods__["idup"] = _FreesteelPython.ckpline_idup_set
    __swig_getmethods__["idup"] = _FreesteelPython.ckpline_idup_get
    if _newclass:idup = _swig_property(_FreesteelPython.ckpline_idup_get, _FreesteelPython.ckpline_idup_set)
    __swig_setmethods__["vmid"] = _FreesteelPython.ckpline_vmid_set
    __swig_getmethods__["vmid"] = _FreesteelPython.ckpline_vmid_get
    if _newclass:vmid = _swig_property(_FreesteelPython.ckpline_vmid_get, _FreesteelPython.ckpline_vmid_set)
    __swig_setmethods__["vrad"] = _FreesteelPython.ckpline_vrad_set
    __swig_getmethods__["vrad"] = _FreesteelPython.ckpline_vrad_get
    if _newclass:vrad = _swig_property(_FreesteelPython.ckpline_vrad_get, _FreesteelPython.ckpline_vrad_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_ckpline(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_ckpline
    __del__ = lambda self : None;
ckpline_swigregister = _FreesteelPython.ckpline_swigregister
ckpline_swigregister(ckpline)

class pucketX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pucketX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pucketX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ckpoints"] = _FreesteelPython.pucketX_ckpoints_set
    __swig_getmethods__["ckpoints"] = _FreesteelPython.pucketX_ckpoints_get
    if _newclass:ckpoints = _swig_property(_FreesteelPython.pucketX_ckpoints_get, _FreesteelPython.pucketX_ckpoints_set)
    __swig_setmethods__["cklines"] = _FreesteelPython.pucketX_cklines_set
    __swig_getmethods__["cklines"] = _FreesteelPython.pucketX_cklines_get
    if _newclass:cklines = _swig_property(_FreesteelPython.pucketX_cklines_get, _FreesteelPython.pucketX_cklines_set)
    def __init__(self): 
        this = _FreesteelPython.new_pucketX()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_pucketX
    __del__ = lambda self : None;
pucketX_swigregister = _FreesteelPython.pucketX_swigregister
pucketX_swigregister(pucketX)

class PathXboxed(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PathXboxed, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PathXboxed, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ppathx"] = _FreesteelPython.PathXboxed_ppathx_set
    __swig_getmethods__["ppathx"] = _FreesteelPython.PathXboxed_ppathx_get
    if _newclass:ppathx = _swig_property(_FreesteelPython.PathXboxed_ppathx_get, _FreesteelPython.PathXboxed_ppathx_set)
    __swig_setmethods__["gburg"] = _FreesteelPython.PathXboxed_gburg_set
    __swig_getmethods__["gburg"] = _FreesteelPython.PathXboxed_gburg_get
    if _newclass:gburg = _swig_property(_FreesteelPython.PathXboxed_gburg_get, _FreesteelPython.PathXboxed_gburg_set)
    __swig_setmethods__["bGeoOutLeft"] = _FreesteelPython.PathXboxed_bGeoOutLeft_set
    __swig_getmethods__["bGeoOutLeft"] = _FreesteelPython.PathXboxed_bGeoOutLeft_get
    if _newclass:bGeoOutLeft = _swig_property(_FreesteelPython.PathXboxed_bGeoOutLeft_get, _FreesteelPython.PathXboxed_bGeoOutLeft_set)
    __swig_setmethods__["bGeoOutRight"] = _FreesteelPython.PathXboxed_bGeoOutRight_set
    __swig_getmethods__["bGeoOutRight"] = _FreesteelPython.PathXboxed_bGeoOutRight_get
    if _newclass:bGeoOutRight = _swig_property(_FreesteelPython.PathXboxed_bGeoOutRight_get, _FreesteelPython.PathXboxed_bGeoOutRight_set)
    __swig_setmethods__["upart"] = _FreesteelPython.PathXboxed_upart_set
    __swig_getmethods__["upart"] = _FreesteelPython.PathXboxed_upart_get
    if _newclass:upart = _swig_property(_FreesteelPython.PathXboxed_upart_get, _FreesteelPython.PathXboxed_upart_set)
    __swig_setmethods__["puckets"] = _FreesteelPython.PathXboxed_puckets_set
    __swig_getmethods__["puckets"] = _FreesteelPython.PathXboxed_puckets_get
    if _newclass:puckets = _swig_property(_FreesteelPython.PathXboxed_puckets_get, _FreesteelPython.PathXboxed_puckets_set)
    __swig_setmethods__["tsbound"] = _FreesteelPython.PathXboxed_tsbound_set
    __swig_getmethods__["tsbound"] = _FreesteelPython.PathXboxed_tsbound_get
    if _newclass:tsbound = _swig_property(_FreesteelPython.PathXboxed_tsbound_get, _FreesteelPython.PathXboxed_tsbound_set)
    __swig_setmethods__["idups"] = _FreesteelPython.PathXboxed_idups_set
    __swig_getmethods__["idups"] = _FreesteelPython.PathXboxed_idups_get
    if _newclass:idups = _swig_property(_FreesteelPython.PathXboxed_idups_get, _FreesteelPython.PathXboxed_idups_set)
    __swig_setmethods__["maxidup"] = _FreesteelPython.PathXboxed_maxidup_set
    __swig_getmethods__["maxidup"] = _FreesteelPython.PathXboxed_maxidup_get
    if _newclass:maxidup = _swig_property(_FreesteelPython.PathXboxed_maxidup_get, _FreesteelPython.PathXboxed_maxidup_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_PathXboxed(*args)
        try: self.this.append(this)
        except: self.this = this
    def BuildBoxes(self, *args): return _FreesteelPython.PathXboxed_BuildBoxes(self, *args)
    def PutSegment(self, *args): return _FreesteelPython.PathXboxed_PutSegment(self, *args)
    def Add(self, *args): return _FreesteelPython.PathXboxed_Add(self, *args)
    def Break(self): return _FreesteelPython.PathXboxed_Break(self)
    def Pop_back(self): return _FreesteelPython.PathXboxed_Pop_back(self)
    __swig_destroy__ = _FreesteelPython.delete_PathXboxed
    __del__ = lambda self : None;
PathXboxed_swigregister = _FreesteelPython.PathXboxed_swigregister
PathXboxed_swigregister(PathXboxed)

class edgeX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, edgeX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, edgeX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p0"] = _FreesteelPython.edgeX_p0_set
    __swig_getmethods__["p0"] = _FreesteelPython.edgeX_p0_get
    if _newclass:p0 = _swig_property(_FreesteelPython.edgeX_p0_get, _FreesteelPython.edgeX_p0_set)
    __swig_setmethods__["p1"] = _FreesteelPython.edgeX_p1_set
    __swig_getmethods__["p1"] = _FreesteelPython.edgeX_p1_get
    if _newclass:p1 = _swig_property(_FreesteelPython.edgeX_p1_get, _FreesteelPython.edgeX_p1_set)
    __swig_setmethods__["tpR"] = _FreesteelPython.edgeX_tpR_set
    __swig_getmethods__["tpR"] = _FreesteelPython.edgeX_tpR_get
    if _newclass:tpR = _swig_property(_FreesteelPython.edgeX_tpR_get, _FreesteelPython.edgeX_tpR_set)
    __swig_setmethods__["tpL"] = _FreesteelPython.edgeX_tpL_set
    __swig_getmethods__["tpL"] = _FreesteelPython.edgeX_tpL_get
    if _newclass:tpL = _swig_property(_FreesteelPython.edgeX_tpL_get, _FreesteelPython.edgeX_tpL_set)
    __swig_setmethods__["rdR"] = _FreesteelPython.edgeX_rdR_set
    __swig_getmethods__["rdR"] = _FreesteelPython.edgeX_rdR_get
    if _newclass:rdR = _swig_property(_FreesteelPython.edgeX_rdR_get, _FreesteelPython.edgeX_rdR_set)
    __swig_setmethods__["rdL"] = _FreesteelPython.edgeX_rdL_set
    __swig_getmethods__["rdL"] = _FreesteelPython.edgeX_rdL_get
    if _newclass:rdL = _swig_property(_FreesteelPython.edgeX_rdL_get, _FreesteelPython.edgeX_rdL_set)
    __swig_setmethods__["sidecheck4"] = _FreesteelPython.edgeX_sidecheck4_set
    __swig_getmethods__["sidecheck4"] = _FreesteelPython.edgeX_sidecheck4_get
    if _newclass:sidecheck4 = _swig_property(_FreesteelPython.edgeX_sidecheck4_get, _FreesteelPython.edgeX_sidecheck4_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_edgeX(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_edgeX
    __del__ = lambda self : None;
edgeX_swigregister = _FreesteelPython.edgeX_swigregister
edgeX_swigregister(edgeX)

class triangX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, triangX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, triangX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ab1"] = _FreesteelPython.triangX_ab1_set
    __swig_getmethods__["ab1"] = _FreesteelPython.triangX_ab1_get
    if _newclass:ab1 = _swig_property(_FreesteelPython.triangX_ab1_get, _FreesteelPython.triangX_ab1_set)
    __swig_setmethods__["ab2"] = _FreesteelPython.triangX_ab2_set
    __swig_getmethods__["ab2"] = _FreesteelPython.triangX_ab2_get
    if _newclass:ab2 = _swig_property(_FreesteelPython.triangX_ab2_get, _FreesteelPython.triangX_ab2_set)
    __swig_setmethods__["b12"] = _FreesteelPython.triangX_b12_set
    __swig_getmethods__["b12"] = _FreesteelPython.triangX_b12_get
    if _newclass:b12 = _swig_property(_FreesteelPython.triangX_b12_get, _FreesteelPython.triangX_b12_set)
    __swig_setmethods__["tnorm"] = _FreesteelPython.triangX_tnorm_set
    __swig_getmethods__["tnorm"] = _FreesteelPython.triangX_tnorm_get
    if _newclass:tnorm = _swig_property(_FreesteelPython.triangX_tnorm_get, _FreesteelPython.triangX_tnorm_set)
    __swig_setmethods__["tp"] = _FreesteelPython.triangX_tp_set
    __swig_getmethods__["tp"] = _FreesteelPython.triangX_tp_get
    if _newclass:tp = _swig_property(_FreesteelPython.triangX_tp_get, _FreesteelPython.triangX_tp_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_triangX(*args)
        try: self.this.append(this)
        except: self.this = this
    def SetEdge(self, *args): return _FreesteelPython.triangX_SetEdge(self, *args)
    def FirstPoint(self): return _FreesteelPython.triangX_FirstPoint(self)
    def SecondPoint(self): return _FreesteelPython.triangX_SecondPoint(self)
    def ThirdPoint(self, *args): return _FreesteelPython.triangX_ThirdPoint(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_triangX
    __del__ = lambda self : None;
triangX_swigregister = _FreesteelPython.triangX_swigregister
triangX_swigregister(triangX)

class SurfX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SurfX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SurfX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gxrg"] = _FreesteelPython.SurfX_gxrg_set
    __swig_getmethods__["gxrg"] = _FreesteelPython.SurfX_gxrg_get
    if _newclass:gxrg = _swig_property(_FreesteelPython.SurfX_gxrg_get, _FreesteelPython.SurfX_gxrg_set)
    __swig_setmethods__["gyrg"] = _FreesteelPython.SurfX_gyrg_set
    __swig_getmethods__["gyrg"] = _FreesteelPython.SurfX_gyrg_get
    if _newclass:gyrg = _swig_property(_FreesteelPython.SurfX_gyrg_get, _FreesteelPython.SurfX_gyrg_set)
    __swig_setmethods__["gzrg"] = _FreesteelPython.SurfX_gzrg_set
    __swig_getmethods__["gzrg"] = _FreesteelPython.SurfX_gzrg_get
    if _newclass:gzrg = _swig_property(_FreesteelPython.SurfX_gzrg_get, _FreesteelPython.SurfX_gzrg_set)
    __swig_setmethods__["rangestate"] = _FreesteelPython.SurfX_rangestate_set
    __swig_getmethods__["rangestate"] = _FreesteelPython.SurfX_rangestate_get
    if _newclass:rangestate = _swig_property(_FreesteelPython.SurfX_rangestate_get, _FreesteelPython.SurfX_rangestate_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_SurfX(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["lvd"] = _FreesteelPython.SurfX_lvd_set
    __swig_getmethods__["lvd"] = _FreesteelPython.SurfX_lvd_get
    if _newclass:lvd = _swig_property(_FreesteelPython.SurfX_lvd_get, _FreesteelPython.SurfX_lvd_set)
    __swig_setmethods__["ltd"] = _FreesteelPython.SurfX_ltd_set
    __swig_getmethods__["ltd"] = _FreesteelPython.SurfX_ltd_get
    if _newclass:ltd = _swig_property(_FreesteelPython.SurfX_ltd_get, _FreesteelPython.SurfX_ltd_set)
    def PushTriangle(self, *args): return _FreesteelPython.SurfX_PushTriangle(self, *args)
    def ReadStlFile(self, *args): return _FreesteelPython.SurfX_ReadStlFile(self, *args)
    __swig_setmethods__["vdX"] = _FreesteelPython.SurfX_vdX_set
    __swig_getmethods__["vdX"] = _FreesteelPython.SurfX_vdX_get
    if _newclass:vdX = _swig_property(_FreesteelPython.SurfX_vdX_get, _FreesteelPython.SurfX_vdX_set)
    __swig_setmethods__["edX"] = _FreesteelPython.SurfX_edX_set
    __swig_getmethods__["edX"] = _FreesteelPython.SurfX_edX_get
    if _newclass:edX = _swig_property(_FreesteelPython.SurfX_edX_get, _FreesteelPython.SurfX_edX_set)
    __swig_setmethods__["trX"] = _FreesteelPython.SurfX_trX_set
    __swig_getmethods__["trX"] = _FreesteelPython.SurfX_trX_get
    if _newclass:trX = _swig_property(_FreesteelPython.SurfX_trX_get, _FreesteelPython.SurfX_trX_set)
    def BuildComponents(self): return _FreesteelPython.SurfX_BuildComponents(self)
    def SliceFibre(self, *args): return _FreesteelPython.SurfX_SliceFibre(self, *args)
    def SliceRay(self, *args): return _FreesteelPython.SurfX_SliceRay(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_SurfX
    __del__ = lambda self : None;
SurfX_swigregister = _FreesteelPython.SurfX_swigregister
SurfX_swigregister(SurfX)

class ckedgeX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ckedgeX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ckedgeX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["zh"] = _FreesteelPython.ckedgeX_zh_set
    __swig_getmethods__["zh"] = _FreesteelPython.ckedgeX_zh_get
    if _newclass:zh = _swig_property(_FreesteelPython.ckedgeX_zh_get, _FreesteelPython.ckedgeX_zh_set)
    __swig_setmethods__["edx"] = _FreesteelPython.ckedgeX_edx_set
    __swig_getmethods__["edx"] = _FreesteelPython.ckedgeX_edx_get
    if _newclass:edx = _swig_property(_FreesteelPython.ckedgeX_edx_get, _FreesteelPython.ckedgeX_edx_set)
    __swig_setmethods__["idup"] = _FreesteelPython.ckedgeX_idup_set
    __swig_getmethods__["idup"] = _FreesteelPython.ckedgeX_idup_get
    if _newclass:idup = _swig_property(_FreesteelPython.ckedgeX_idup_get, _FreesteelPython.ckedgeX_idup_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_ckedgeX(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_ckedgeX
    __del__ = lambda self : None;
ckedgeX_swigregister = _FreesteelPython.ckedgeX_swigregister
ckedgeX_swigregister(ckedgeX)

class cktriX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cktriX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cktriX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["zh"] = _FreesteelPython.cktriX_zh_set
    __swig_getmethods__["zh"] = _FreesteelPython.cktriX_zh_get
    if _newclass:zh = _swig_property(_FreesteelPython.cktriX_zh_get, _FreesteelPython.cktriX_zh_set)
    __swig_setmethods__["trx"] = _FreesteelPython.cktriX_trx_set
    __swig_getmethods__["trx"] = _FreesteelPython.cktriX_trx_get
    if _newclass:trx = _swig_property(_FreesteelPython.cktriX_trx_get, _FreesteelPython.cktriX_trx_set)
    __swig_setmethods__["idup"] = _FreesteelPython.cktriX_idup_set
    __swig_getmethods__["idup"] = _FreesteelPython.cktriX_idup_get
    if _newclass:idup = _swig_property(_FreesteelPython.cktriX_idup_get, _FreesteelPython.cktriX_idup_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_cktriX(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_cktriX
    __del__ = lambda self : None;
cktriX_swigregister = _FreesteelPython.cktriX_swigregister
cktriX_swigregister(cktriX)

class bucketX(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bucketX, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bucketX, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ckpoints"] = _FreesteelPython.bucketX_ckpoints_set
    __swig_getmethods__["ckpoints"] = _FreesteelPython.bucketX_ckpoints_get
    if _newclass:ckpoints = _swig_property(_FreesteelPython.bucketX_ckpoints_get, _FreesteelPython.bucketX_ckpoints_set)
    __swig_setmethods__["ckedges"] = _FreesteelPython.bucketX_ckedges_set
    __swig_getmethods__["ckedges"] = _FreesteelPython.bucketX_ckedges_get
    if _newclass:ckedges = _swig_property(_FreesteelPython.bucketX_ckedges_get, _FreesteelPython.bucketX_ckedges_set)
    __swig_setmethods__["cktriangs"] = _FreesteelPython.bucketX_cktriangs_set
    __swig_getmethods__["cktriangs"] = _FreesteelPython.bucketX_cktriangs_get
    if _newclass:cktriangs = _swig_property(_FreesteelPython.bucketX_cktriangs_get, _FreesteelPython.bucketX_cktriangs_set)
    def __init__(self): 
        this = _FreesteelPython.new_bucketX()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_bucketX
    __del__ = lambda self : None;
bucketX_swigregister = _FreesteelPython.bucketX_swigregister
bucketX_swigregister(bucketX)

class SurfXboxed(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SurfXboxed, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SurfXboxed, name)
    __repr__ = _swig_repr
    __swig_setmethods__["psurfx"] = _FreesteelPython.SurfXboxed_psurfx_set
    __swig_getmethods__["psurfx"] = _FreesteelPython.SurfXboxed_psurfx_get
    if _newclass:psurfx = _swig_property(_FreesteelPython.SurfXboxed_psurfx_get, _FreesteelPython.SurfXboxed_psurfx_set)
    __swig_setmethods__["gbxrg"] = _FreesteelPython.SurfXboxed_gbxrg_set
    __swig_getmethods__["gbxrg"] = _FreesteelPython.SurfXboxed_gbxrg_get
    if _newclass:gbxrg = _swig_property(_FreesteelPython.SurfXboxed_gbxrg_get, _FreesteelPython.SurfXboxed_gbxrg_set)
    __swig_setmethods__["gbyrg"] = _FreesteelPython.SurfXboxed_gbyrg_set
    __swig_getmethods__["gbyrg"] = _FreesteelPython.SurfXboxed_gbyrg_get
    if _newclass:gbyrg = _swig_property(_FreesteelPython.SurfXboxed_gbyrg_get, _FreesteelPython.SurfXboxed_gbyrg_set)
    __swig_setmethods__["bGeoOutLeft"] = _FreesteelPython.SurfXboxed_bGeoOutLeft_set
    __swig_getmethods__["bGeoOutLeft"] = _FreesteelPython.SurfXboxed_bGeoOutLeft_get
    if _newclass:bGeoOutLeft = _swig_property(_FreesteelPython.SurfXboxed_bGeoOutLeft_get, _FreesteelPython.SurfXboxed_bGeoOutLeft_set)
    __swig_setmethods__["bGeoOutUp"] = _FreesteelPython.SurfXboxed_bGeoOutUp_set
    __swig_getmethods__["bGeoOutUp"] = _FreesteelPython.SurfXboxed_bGeoOutUp_get
    if _newclass:bGeoOutUp = _swig_property(_FreesteelPython.SurfXboxed_bGeoOutUp_get, _FreesteelPython.SurfXboxed_bGeoOutUp_set)
    __swig_setmethods__["bGeoOutRight"] = _FreesteelPython.SurfXboxed_bGeoOutRight_set
    __swig_getmethods__["bGeoOutRight"] = _FreesteelPython.SurfXboxed_bGeoOutRight_get
    if _newclass:bGeoOutRight = _swig_property(_FreesteelPython.SurfXboxed_bGeoOutRight_get, _FreesteelPython.SurfXboxed_bGeoOutRight_set)
    __swig_setmethods__["bGeoOutDown"] = _FreesteelPython.SurfXboxed_bGeoOutDown_set
    __swig_getmethods__["bGeoOutDown"] = _FreesteelPython.SurfXboxed_bGeoOutDown_get
    if _newclass:bGeoOutDown = _swig_property(_FreesteelPython.SurfXboxed_bGeoOutDown_get, _FreesteelPython.SurfXboxed_bGeoOutDown_set)
    __swig_setmethods__["xpart"] = _FreesteelPython.SurfXboxed_xpart_set
    __swig_getmethods__["xpart"] = _FreesteelPython.SurfXboxed_xpart_get
    if _newclass:xpart = _swig_property(_FreesteelPython.SurfXboxed_xpart_get, _FreesteelPython.SurfXboxed_xpart_set)
    __swig_setmethods__["yparts"] = _FreesteelPython.SurfXboxed_yparts_set
    __swig_getmethods__["yparts"] = _FreesteelPython.SurfXboxed_yparts_get
    if _newclass:yparts = _swig_property(_FreesteelPython.SurfXboxed_yparts_get, _FreesteelPython.SurfXboxed_yparts_set)
    __swig_setmethods__["buckets"] = _FreesteelPython.SurfXboxed_buckets_set
    __swig_getmethods__["buckets"] = _FreesteelPython.SurfXboxed_buckets_get
    if _newclass:buckets = _swig_property(_FreesteelPython.SurfXboxed_buckets_get, _FreesteelPython.SurfXboxed_buckets_set)
    __swig_setmethods__["idups"] = _FreesteelPython.SurfXboxed_idups_set
    __swig_getmethods__["idups"] = _FreesteelPython.SurfXboxed_idups_get
    if _newclass:idups = _swig_property(_FreesteelPython.SurfXboxed_idups_get, _FreesteelPython.SurfXboxed_idups_set)
    __swig_setmethods__["maxidup"] = _FreesteelPython.SurfXboxed_maxidup_set
    __swig_getmethods__["maxidup"] = _FreesteelPython.SurfXboxed_maxidup_get
    if _newclass:maxidup = _swig_property(_FreesteelPython.SurfXboxed_maxidup_get, _FreesteelPython.SurfXboxed_maxidup_set)
    def __init__(self, *args): 
        this = _FreesteelPython.new_SurfXboxed(*args)
        try: self.this.append(this)
        except: self.this = this
    def AddPointBucket(self, *args): return _FreesteelPython.SurfXboxed_AddPointBucket(self, *args)
    def AddEdgeBucket(self, *args): return _FreesteelPython.SurfXboxed_AddEdgeBucket(self, *args)
    def AddTriangBucket(self, *args): return _FreesteelPython.SurfXboxed_AddTriangBucket(self, *args)
    def SortBuckets(self): return _FreesteelPython.SurfXboxed_SortBuckets(self)
    def BuildBoxes(self, *args): return _FreesteelPython.SurfXboxed_BuildBoxes(self, *args)
    __swig_setmethods__["searchbox_epsilon"] = _FreesteelPython.SurfXboxed_searchbox_epsilon_set
    __swig_getmethods__["searchbox_epsilon"] = _FreesteelPython.SurfXboxed_searchbox_epsilon_get
    if _newclass:searchbox_epsilon = _swig_property(_FreesteelPython.SurfXboxed_searchbox_epsilon_get, _FreesteelPython.SurfXboxed_searchbox_epsilon_set)
    def SliceFibreBox(self, *args): return _FreesteelPython.SurfXboxed_SliceFibreBox(self, *args)
    def SliceUFibre(self, *args): return _FreesteelPython.SurfXboxed_SliceUFibre(self, *args)
    def SliceVFibre(self, *args): return _FreesteelPython.SurfXboxed_SliceVFibre(self, *args)
    __swig_destroy__ = _FreesteelPython.delete_SurfXboxed
    __del__ = lambda self : None;
SurfXboxed_swigregister = _FreesteelPython.SurfXboxed_swigregister
SurfXboxed_swigregister(SurfXboxed)

class S2weaveB1iter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, S2weaveB1iter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, S2weaveB1iter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ftype"] = _FreesteelPython.S2weaveB1iter_ftype_set
    __swig_getmethods__["ftype"] = _FreesteelPython.S2weaveB1iter_ftype_get
    if _newclass:ftype = _swig_property(_FreesteelPython.S2weaveB1iter_ftype_get, _FreesteelPython.S2weaveB1iter_ftype_set)
    __swig_setmethods__["blower"] = _FreesteelPython.S2weaveB1iter_blower_set
    __swig_getmethods__["blower"] = _FreesteelPython.S2weaveB1iter_blower_get
    if _newclass:blower = _swig_property(_FreesteelPython.S2weaveB1iter_blower_get, _FreesteelPython.S2weaveB1iter_blower_set)
    __swig_setmethods__["w"] = _FreesteelPython.S2weaveB1iter_w_set
    __swig_getmethods__["w"] = _FreesteelPython.S2weaveB1iter_w_get
    if _newclass:w = _swig_property(_FreesteelPython.S2weaveB1iter_w_get, _FreesteelPython.S2weaveB1iter_w_set)
    __swig_setmethods__["wp"] = _FreesteelPython.S2weaveB1iter_wp_set
    __swig_getmethods__["wp"] = _FreesteelPython.S2weaveB1iter_wp_get
    if _newclass:wp = _swig_property(_FreesteelPython.S2weaveB1iter_wp_get, _FreesteelPython.S2weaveB1iter_wp_set)
    __swig_setmethods__["ixwp"] = _FreesteelPython.S2weaveB1iter_ixwp_set
    __swig_getmethods__["ixwp"] = _FreesteelPython.S2weaveB1iter_ixwp_get
    if _newclass:ixwp = _swig_property(_FreesteelPython.S2weaveB1iter_ixwp_get, _FreesteelPython.S2weaveB1iter_ixwp_set)
    def GetPoint(self): return _FreesteelPython.S2weaveB1iter_GetPoint(self)
    def __init__(self): 
        this = _FreesteelPython.new_S2weaveB1iter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_S2weaveB1iter
    __del__ = lambda self : None;
S2weaveB1iter_swigregister = _FreesteelPython.S2weaveB1iter_swigregister
S2weaveB1iter_swigregister(S2weaveB1iter)

class S2weave(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, S2weave, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, S2weave, name)
    __repr__ = _swig_repr
    __swig_setmethods__["urg"] = _FreesteelPython.S2weave_urg_set
    __swig_getmethods__["urg"] = _FreesteelPython.S2weave_urg_get
    if _newclass:urg = _swig_property(_FreesteelPython.S2weave_urg_get, _FreesteelPython.S2weave_urg_set)
    __swig_setmethods__["vrg"] = _FreesteelPython.S2weave_vrg_set
    __swig_getmethods__["vrg"] = _FreesteelPython.S2weave_vrg_get
    if _newclass:vrg = _swig_property(_FreesteelPython.S2weave_vrg_get, _FreesteelPython.S2weave_vrg_set)
    __swig_setmethods__["ufibs"] = _FreesteelPython.S2weave_ufibs_set
    __swig_getmethods__["ufibs"] = _FreesteelPython.S2weave_ufibs_get
    if _newclass:ufibs = _swig_property(_FreesteelPython.S2weave_ufibs_get, _FreesteelPython.S2weave_ufibs_set)
    __swig_setmethods__["vfibs"] = _FreesteelPython.S2weave_vfibs_set
    __swig_getmethods__["vfibs"] = _FreesteelPython.S2weave_vfibs_get
    if _newclass:vfibs = _swig_property(_FreesteelPython.S2weave_vfibs_get, _FreesteelPython.S2weave_vfibs_set)
    __swig_setmethods__["firstcontournumber"] = _FreesteelPython.S2weave_firstcontournumber_set
    __swig_getmethods__["firstcontournumber"] = _FreesteelPython.S2weave_firstcontournumber_get
    if _newclass:firstcontournumber = _swig_property(_FreesteelPython.S2weave_firstcontournumber_get, _FreesteelPython.S2weave_firstcontournumber_set)
    __swig_setmethods__["lastcontournumber"] = _FreesteelPython.S2weave_lastcontournumber_set
    __swig_getmethods__["lastcontournumber"] = _FreesteelPython.S2weave_lastcontournumber_get
    if _newclass:lastcontournumber = _swig_property(_FreesteelPython.S2weave_lastcontournumber_get, _FreesteelPython.S2weave_lastcontournumber_set)
    def SetShape(self, *args): return _FreesteelPython.S2weave_SetShape(self, *args)
    def Advance(self, *args): return _FreesteelPython.S2weave_Advance(self, *args)
    def ContourNumber(self, *args): return _FreesteelPython.S2weave_ContourNumber(self, *args)
    def TrackContour(self, *args): return _FreesteelPython.S2weave_TrackContour(self, *args)
    def SetAllCutCodes(self, *args): return _FreesteelPython.S2weave_SetAllCutCodes(self, *args)
    def Invert(self): return _FreesteelPython.S2weave_Invert(self)
    def __init__(self): 
        this = _FreesteelPython.new_S2weave()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_S2weave
    __del__ = lambda self : None;
S2weave_swigregister = _FreesteelPython.S2weave_swigregister
S2weave_swigregister(S2weave)


def CircleIntersectNew(*args):
  return _FreesteelPython.CircleIntersectNew(*args)
CircleIntersectNew = _FreesteelPython.CircleIntersectNew

def HackAreaOffset(*args):
  return _FreesteelPython.HackAreaOffset(*args)
HackAreaOffset = _FreesteelPython.HackAreaOffset

def HackToolpath(*args):
  return _FreesteelPython.HackToolpath(*args)
HackToolpath = _FreesteelPython.HackToolpath
class Area2_gen(S2weave):
    __swig_setmethods__ = {}
    for _s in [S2weave]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Area2_gen, name, value)
    __swig_getmethods__ = {}
    for _s in [S2weave]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Area2_gen, name)
    __repr__ = _swig_repr
    __swig_setmethods__["z"] = _FreesteelPython.Area2_gen_z_set
    __swig_getmethods__["z"] = _FreesteelPython.Area2_gen_z_get
    if _newclass:z = _swig_property(_FreesteelPython.Area2_gen_z_get, _FreesteelPython.Area2_gen_z_set)
    __swig_setmethods__["r"] = _FreesteelPython.Area2_gen_r_set
    __swig_getmethods__["r"] = _FreesteelPython.Area2_gen_r_get
    if _newclass:r = _swig_property(_FreesteelPython.Area2_gen_r_get, _FreesteelPython.Area2_gen_r_set)
    __swig_setmethods__["psxb"] = _FreesteelPython.Area2_gen_psxb_set
    __swig_getmethods__["psxb"] = _FreesteelPython.Area2_gen_psxb_get
    if _newclass:psxb = _swig_property(_FreesteelPython.Area2_gen_psxb_get, _FreesteelPython.Area2_gen_psxb_set)
    def SetSurfaceTop(self, *args): return _FreesteelPython.Area2_gen_SetSurfaceTop(self, *args)
    def HackDowntoZ(self, *args): return _FreesteelPython.Area2_gen_HackDowntoZ(self, *args)
    def FindInterior(self, *args): return _FreesteelPython.Area2_gen_FindInterior(self, *args)
    def MakeContours(self, *args): return _FreesteelPython.Area2_gen_MakeContours(self, *args)
    def __init__(self): 
        this = _FreesteelPython.new_Area2_gen()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _FreesteelPython.delete_Area2_gen
    __del__ = lambda self : None;
Area2_gen_swigregister = _FreesteelPython.Area2_gen_swigregister
Area2_gen_swigregister(Area2_gen)

# This file is compatible with both classic and new-style classes.


